### ISSUE TITLE
docs: include the ffmpeg command to output a low resolution video

### ISSUE THREAD

**Issue by notthetup** [sayanee/build-podcast#65]

**Comment by prathamesh-sonpatki** [comment]
:+1:

**Comment by sayanee** [comment]
try this:

```
ffmpeg -i input.mov -r 25 -b:v 500k output.mov
```

**Comment by prathamesh-sonpatki** [comment]
@sayanee Will it work if I change output.mov to output.mp4?

**Comment by sayanee** [comment]
Should be fine as [MOV and MP4 container formats can use the same MPEG-4 formats](http://en.wikipedia.org/wiki/QuickTime_File_Format#Relation_to_MP4).

I just tried to export as `Share > File` in *iMovie* for a 3:28min `*.mp4` movie that was initially `54MB`.

```
ffmpeg -i input.mp4 -r 25 -b:v 500k output.mp4
```

The result is `output.mp4` with 14MB size.
