### ISSUE TITLE
The following tutorial is awsome but have some question

### ISSUE THREAD

**Issue by abhisekroy2002** [sayanee/build-podcast#69]
In this "062 mocha" episode the code coverage part is not working, I have tried with so many things, but still coverage is coming as 0% could u please check and tell me what is the issue I want to know this. I am using windows is that a issue?

**Comment by sayanee** [comment]
No enough information to help you with this. Maybe you can post a question on [Stackoverflow with mocha and code-coverage](http://stackoverflow.com/search?q=mocha) as tags?
