### ISSUE TITLE
Miss your videos...

### ISSUE THREAD

**Issue by awakekat** [sayanee/build-podcast#70]
Hey Sayanee,
Glad to hear your coming back. As a "girl geek" I have missed you/your videos. Your a great teacher - coming from a teacher too. I will check back in with you in July! 
Happy Coding, Building and Podcasting!

**Comment by sayanee** [comment]
Hey thanks so much @awakekat :sparkles: 

Yes, give me a couple of months to shift my home and I will restart learning by sharing with Build Podcast!
