### ISSUE TITLE
Build Podcast 62 Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.

### ISSUE THREAD

**Issue by lacostenycoder** [sayanee/build-podcast#71]
Everything is working fine except in the browser section when I run the mocha test it fails regardless of
how long I set timeout.  I've verified that java jar server is running and node server as well.  

mocha indexSpec.js --timeout 50000

1) from Homepage "before each" hook for "return the title of the page":
     Error: timeout of 50000ms exceeded. Ensure the done() callback is being called in this test.
  

  2) from Homepage "after all" hook for "return the title of the page":
     Error: timeout of 50000ms exceeded. Ensure the done() callback is being called in this test.

The behavior I experience is that mocha test launches a new instance of chrome, but in the URL which shows in the new chrome browser address bar doesn't appear to be going to http://localhost:8000 but rather simply " data:, "  Any ideas why ?   Thanks.

![image](https://cloud.githubusercontent.com/assets/6077905/9899147/df020e98-5c25-11e5-82d8-4b684e123cf6.png)

**Comment by sayanee** [comment]
Hi @lacostenycoder, I hope your issue is solved? 

It would be better to ask [Stackoverflow](https://stackoverflow.com/) of [mocha's chat](https://mochajs.org/#more-information) as well as this is mocha specific.
