### ISSUE TITLE
undefined local variable or method `tasks_without_stage_dependency'

### ISSUE THREAD

**Issue by whoru7777777** [sayanee/build-podcast#73]
Hello I have been stuck here for days, I would really appreciate help. I have been to many site uninstalled  and re-installed etceteras. Here is my error log. I am using Rails 4.2.3, Ruby 2.1.7-p400, Capistrano Version: 3.4.0 (Rake Version: 10.4.2), and the latest rubber gem. It seems rubber installed without error and bundles work as well as general rake and rails sever.

$cap rubber:create_staging --trace
cap aborted!
NameError: undefined local variable or method `tasks_without_stage_dependency' for #<Capistrano::Application:0x007ff5fccf3600>

/usr/local/rvm/gems/ruby-2.1.7/gems/capistrano-3.4.0/lib/capistrano/application.rb:57:in `top_level_tasks'
/usr/local/rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/usr/local/rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/usr/local/rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/usr/local/rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/usr/local/rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.1.7/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/usr/local/rvm/gems/ruby-2.1.7/gems/capistrano-3.4.0/lib/capistrano/application.rb:15:in `run'
/usr/local/rvm/gems/ruby-2.1.7/gems/capistrano-3.4.0/bin/cap:3:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.7/bin/cap:23:in `load'
/usr/local/rvm/gems/ruby-2.1.7/bin/cap:23:in `<main>'
/usr/local/rvm/gems/ruby-2.1.7/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.7/bin/ruby_executable_hooks:15:in `<main>'

**Comment by sayanee** [comment]
Please raise this issue in [Capistrano related channels or Stackoverflow](https://github.com/sayanee/build-podcast/blob/master/CONTRIBUTING.md#for-tool-specific-questions).
